apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: dirver-monitor
spec:
  selector:
    matchLabels:
      dataproc.googleapis.com/role: driver
  endpoints:
    - port: 9091
      path: /metrics
      interval: 5s

---
apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: executor-monitor
spec:
  selector:
    matchLabels:
      spark-role: executor
  endpoints:
    - port: 9091
      path: /metrics
      interval: 5s